Update fail-to-mount-azure-file-share.md
MicrosoftDocs/SupportArticles-docs pull request #1293
Opened 2023-10-17 20:56 UTC by hanagapal

Added Cause 5 :
 The below is documentation improvement bug to avoid support cases and CRIs 
Bug 25433172: unable to mount share with custom security settings(Disabled AES128 GCM)

# Pull request guidance

Thank you for submitting your contribution to our support content! Our team works closely with subject matter experts in CSS and PMs in the product group to review all content requests to ensure technical accuracy and the best customer experience. This process can sometimes take one or more days, so we greatly appreciate your patience.

We also need your help in order to process your request as soon as possible:

- We won't act on your pull request (PR) until you type "**#sign-off**" in a new comment in your pull request (PR) to indicate that your changes are complete.

- After you sign off in your PR, the article will be tech reviewed by the PM or SME if it has more than minor changes. Once the article is approved, it will undergo a final editing pass before being merged.

2023-10-17 21:56 UTC, khdownie requested changes

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              cifsConfPath="/etc/modprobe.d/cifs.conf"
```suggestion
```bash
cifsConfPath="/etc/modprobe.d/cifs.conf" 
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              echo "`date` before change ${cifsConfPath}:"
```suggestion
echo "`date` before change ${cifsConfPath}:"
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              cat ${cifsConfPath}
```suggestion
cat ${cifsConfPath} 
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              if !(( grep require_gcm_256 ${cifsConfPath} ))
```suggestion
if !(( grep require_gcm_256 ${cifsConfPath} )) 
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              then
```suggestion
then
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              modprobe cifs
```suggestion
modprobe cifs
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              echo 1 > /sys/module/cifs/parameters/require_gcm_256
```suggestion
echo 1 > /sys/module/cifs/parameters/require_gcm_256
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              echo "options cifs require_gcm_256=1" > ${cifsConfPath}
```suggestion
echo "options cifs require_gcm_256=1" > ${cifsConfPath}
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              echo "`date` after changing ${cifsConfPath}:"
```suggestion
echo "`date` after changing ${cifsConfPath}:"
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              cat ${cifsConfPath}
```suggestion
cat ${cifsConfPath}
```

2023-10-17 21:56 UTC, khdownie commented on support/azure/azure-kubernetes/fail-to-mount-azure-file-share.md
> +              fi
```suggestion
fi
```
```

2023-10-18 01:22 UTC, AmandaAZ commented
@hanagapal @khdownie I see the same changes are submitted via the private [pull request #5101](https://github.com/MicrosoftDocs/SupportArticles-docs-pr/pull/5101), so I closed this PR. Let me know if any problems.

2023-10-18 01:22 UTC, closed without merging